### ISSUE TITLE
第5版（文字）

### ISSUE THREAD

**Issue by wwmm111** [wwmm111/BP-OE#12]
# 源米站

病从口入，清楚食物的本源，关系到身体健康

你期望，孩子入口的，是原料、加工过程模糊的商品，还是可以追本溯源的食物？

贝贝妈妈最近就遇到了这样的问题
贝贝6个月，需要添加辅食了。

某一天，妈妈为贝贝挑选辅食米粉……
某知名国产品牌（成份）：谷类酶解、钙和维生素D、维生素A、维生素B12、铁和叶酸、维生素C、锌、维生素B1和生物二十二碳六烯酸、碘、低聚糖
某知名进口品牌（成份）：有机大米、有机植物油、铁、维生素C、草本植物
某知名电商品牌（成份）：大米粉、淮山粉、薏米粉、胡萝卜粉、玉米粉、五谷粉
……
贝贝妈妈产生一串疑问： 
微量元素和维生素，是人工合成还是自然提取？
各种成份的原料是什么、产自哪里、怎样种植、质量如何？
6个月的孩子，到底每天需要多少营养元素？
……

贝贝妈妈还搜索到了以下信息：
1999，欧盟奶粉 含 致癌物 二恶英
2002，雅培 销毁 1100吨被 微小金属颗粒、润滑油 污染的婴儿奶粉
2008，三鹿 毒奶粉 事件
2011，欧洲9种品牌 辅食米粉 含 毒性重金属 砷、铅与镉，因 原料大米的土壤被污染
2016，9个月内18批次 进口婴儿辅食 含 工业原料 被销毁
2017，全球排名第三的乳制品企业，疑似新生产线导致奶粉受 沙门氏菌 污染
……

添加的微量元素如何得来？原料的大米干净吗？是否有未标明的成份？

自1928年婴儿辅食商业化起，爸爸妈妈节省了时间，却愈发难以明确孩子入口的食物本源。

贝贝妈妈，想让贝贝多吃一些明确来源、无污染、满足营养需求的食物。

妈妈开始尝试亲自做辅食给贝贝吃，却遭遇了一系列困难。
这款原料大米，贴着“有机”标示却缺乏认证，重金属含量未知，质量可靠吗？
这套辅食配方，未有营养成分明细，能满足贝贝的生长需要吗？
妈妈全职上班，可用于调研、制作辅食的时间极为有限
更何况，贝贝处于人生成长最快的婴幼儿时期，所需要的食物结构一时一变。

如何快速、便捷的获取优质原料和营养辅食配方，让贝贝吃得安全又健康呢？

愁眉不展中，贝贝妈妈收到了一封信：
贝贝妈妈：
源米站 邀请您的孩子，享用可以追本溯源的婴儿辅食。
邀请您和孩子与原料的生长环境亲密接触，
接受营养专家的配方建议，
以父母社区互助的方式，亲自为孩子准备辅食米粉。
孩子吃得安全，父母生活心安。

贝贝妈妈来到源米站，了解情况。
原料区：贝贝妈妈看到每种原料明确的产地、生长环境、质检、认证、营养成份。
比如：原装进口 加拿大黑野米
产地：萨斯喀彻温省北部
生长环境：天然湖水中生长、人工定期补撒种子、水上气艇低于10公里／小时速度采收
质检／认证：TCO，USDA 认证，海关检疫，BIO Suisse 认证
营养成分：

食谱区：贝贝妈妈根据贝贝的年龄、实际发育情况，参考单一原料的营养成分表，根据育儿专家及持牌营养师的建议，为贝贝组合搭配辅食米粉成份

研磨区：贝贝妈妈可以亲自挑选原料、研磨；也可以委托社区内的其他妈妈，根据贝贝妈妈提供的辅食米粉配方，帮助准备辅食米粉，以节省工作时间

产地考察：贝贝妈妈可以带着贝贝去任一原料的产地，亲身体验原料的生长环境。如果贝贝妈妈自愿帮助其他忙碌的妈妈准备孩子们的辅食米粉，达到一定数量，贝贝妈妈和贝贝将免费获得加拿大黑野米产地7日游的机会。

走出米站，贝贝妈妈打开了育儿笔记：
亲爱的贝贝：妈妈挑选良久，只为了确保你吃得安全、营养。妈妈希望你吃的不仅仅是维生素、微量元素、碳水化合物、蛋白质这些营养成分，更是山河大地的馈赠、自然母亲的哺育。希望你从完整的食物中锻炼吸收能力，而不只是靠外力替你选择、提取生长的能量。贝贝，你要平平安安的长大。”

源米站，与您一起，为孩子的健康成长，把握入口，追根溯源。

References
http://www.5h.com/qz/49592.html
http://www.bellamysorganic.cn/product/organic-baby-rice-cereal/#product_tabs1
https://www.precisionnutrition.com/all-about-vitamin-supplements
http://finance.ifeng.com/news/special/meizanchen/
http://www.chinanews.com/cj/2016/11-15/8062874.shtml
http://www.mama.cn/z/24815/
https://www.saskatchewan.ca/business/agriculture-natural-resources-and-industry/agribusiness-farmers-and-ranchers/crops-and-irrigation/specialty-crops/wild-rice
https://www.usask.ca/education/ccstu/pdfs/wildriceappendixa.pdf
http://www.cbc.ca/2017/we-are-the-best/watch-small-sask-producers-harvest-some-of-the-world-s-finest-wild-rice-1.3955941
https://en.wikipedia.org/wiki/Wild_rice
https://www.northernlightsfoods.com/wild-rice

**Comment by ZengGIFT** [comment]
# 源食

- _宝宝吃的食物，
寄托着妈妈的爱，
也是宝宝日渐长大的身体的源头_

- _你希望知道，
孩子的食物源头，
是健康的，寄托着世界的爱。_

- _贝贝妈妈最近就遇到了这样的问题
小宝宝6个月了，除了母乳，还要吃辅食，该吃怎样的呢？_
（添加源头，爱的意像）
----

- 某一天，妈妈为贝贝挑选辅食米粉……
某知名国产品牌（成份）：谷类酶解、钙和维生素D、维生素A、维生素B12、铁和叶酸、维生素C、锌、维生素B1和生物二十二碳六烯酸、碘、低聚糖
某知名进口品牌（成份）：有机大米、有机植物油、铁、维生素C、草本植物
某知名电商品牌（成份）：大米粉、淮山粉、薏米粉、胡萝卜粉、玉米粉、五谷粉

- 贝贝妈妈产生一串疑问：
微量元素和维生素，是人工合成还是自然提取？
各种成份的原料是什么、产自哪里、怎样种植、质量如何？
6个月的孩子，到底每天需要多少营养元素？

- 贝贝妈妈还搜索到了以下信息：
1999，欧盟奶粉 含 致癌物 二恶英
2002，雅培 销毁 1100吨被 微小金属颗粒、润滑油 污染的婴儿奶粉
2008，三鹿 毒奶粉 事件
2011，欧洲9种品牌 辅食米粉 含 毒性重金属 砷、铅与镉，因 原料大米的土壤被污染
2016，9个月内18批次 进口婴儿辅食 含 工业原料 被销毁
2017，全球排名第三的乳制品企业，疑似新生产线导致奶粉受 沙门氏菌 污染

- 添加的微量元素如何得来？原料的大米干净吗？是否有未标明的成份？

- 自1928年婴儿辅食商业化起，
爸爸妈妈节省了时间，
却愈发难以明确孩子入口的食物本源。

贝贝妈妈，想让贝贝多吃一些
明确来源、无污染、满足营养需求的食物。

**却不知道该相信谁**（添加内在冲突）
----

- 妈妈开始尝试亲自做辅食给贝贝吃，却遭遇了一系列困难。
这款原料大米，贴着“有机”标示却缺乏认证，重金属含量未知，质量可靠吗？
这套辅食配方，未有营养成分明细，能满足贝贝的生长需要吗？
妈妈全职上班，可用于调研、制作辅食的时间极为有限
更何况，贝贝处于人生成长最快的婴幼儿时期，所需要的食物结构一时一变。

- 如何快速、便捷的获取优质原料和营养辅食配方，让贝贝吃得安全又健康呢？

- 愁眉不展中，贝贝妈妈听说
_宝儿妈妈在用天然的黑米，亲自为自己的孩子做辅食_
（宝宝妈妈敢相信的，是另一位宝宝妈对孩子的爱）

- 贝贝妈妈来到_**宝儿妈妈家中**_，了解情况。
（商业性的米站 换成 另一位妈妈的家）

----
（同一样一大笔钱，无志者看见的是淫靡；慈善家看见的是帮助他人；创业者看见的是未来；
宝儿妈妈看见的应该不止是 产地和检验，这块还要挖掘；她应该是用五感去观察的，视觉，听觉，嗅觉）
- 原料区：贝贝妈妈看到每种原料明确的产地、生长环境、质检、认证、营养成份。

- 比如：原装进口 加拿大黑野米
产地：萨斯喀彻温省北部
生长环境：天然湖水中生长、人工定期补撒种子、水上气艇低于10公里／小时速度采收
质检／认证：TCO，USDA 认证，海关检疫，BIO Suisse 认证
营养成分：

- 食谱区：贝贝妈妈根据贝贝的年龄、实际发育情况，参考单一原料的营养成分表，根据育儿专家及持牌营养师的建议，为贝贝组合搭配辅食米粉成份

- 研磨区：贝贝妈妈可以亲自挑选原料、研磨；也可以委托社区内的其他妈妈，根据贝贝妈妈提供的辅食米粉配方，帮助准备辅食米粉，以节省工作时间

- 产地考察：贝贝妈妈可以带着贝贝去任一原料的产地，亲身体验原料的生长环境。如果贝贝妈妈自愿帮助其他忙碌的妈妈准备孩子们的辅食米粉，达到一定数量，贝贝妈妈和贝贝将免费获得加拿大黑野米产地7日游的机会。
----
（不需要也是笔记，妈妈抱着宝宝，喃喃自语就行）（语气注意，得是妈妈的语气，而不是厂商的语气）
- 走出米站，贝贝妈妈打开了育儿笔记：
亲爱的贝贝：妈妈挑选良久，只为了确保你吃得安全、营养。妈妈希望你吃的不仅仅是维生素、微量元素、碳水化合物、蛋白质这些营养成分，更是山河大地的馈赠、自然母亲的哺育。希望你从完整的食物中锻炼吸收能力，而不只是靠外力替你选择、提取生长的能量。贝贝，你要平平安安的长大。”

（重新提一下意向，要加强）
- 源米站，与您一起，
为孩子的健康成长，
把握入口，追根溯源。

**Comment by ZengGIFT** [comment]
1. 标注每张卡片的分段
2. 点破文章里一直有，但没有说明的两个意像，母爱和源头（食物是孩子的源头，妈妈是孩子的源头，辅食的源头是美好大自然的恩赐）
3. 添加了一个内在冲突，妈妈想要给宝宝辅食，但不知道该相信谁
4. 把收到信，改成了知道社区里另一个宝宝的妈妈怎么做
