### ISSUE TITLE
新故事 - part 1 - 宝宝自述

### ISSUE THREAD

**Issue by wwmm111** [wwmm111/BP-OE#8]
> **请诸位看看是否与现实冲突，主要不是很清楚现实中宝宝的认知和感官发育顺序** 这个故事简言之：宝宝爱吃母乳，有一天突然没有母奶了，被喂了在宝宝看来各种黑暗的流食，宝宝不高兴就吐奶，饿急了就咽几口，直到有一天发现了别的小伙伴儿不是吃“难吃的奶瓶”，因为好奇被喂了一口别的小伙伴儿的食物，从此发现了母乳的代产品——黑米粉。

我叫李来宝，现年据说6个月。记得有一天，我在暖暖的水池里试图舒展一下腿脚，却感觉到好似有一阵汹涌的波浪袭来。初时还不明显，后来愈加的波涛汹涌。在一阵惊涛骇浪之后，我温暖的水池不见了，冷意和被什么困住的感觉让我忍不住大哭。一张嘴，干冷的空气窜进身体里，我更加想念我温暖的水池。蓦地，我被裹进了一个暖暖的怀抱里，那好像是水池的味道。我忍不住拱了拱这软软暖暖的窝，突然觉得好饿。我循着味道，吃到了人生的第一顿饭。我也不知道吃饱了没有，反正吃着吃着就睡着了。

从此，吃饭成了我除了睡觉之外唯一的大事。可是突然有一天，我使了全身的力气，吃了不知多久，还是很饿很饿。我气得咬了下饭碗，依稀听见了嘤嘤抽噎的声音，还有水滴在我的身上、脸上。我饿得好难受，于是也大声的哭了起来。接着，我被抱离了那个软软暖暖的窝，有什么被塞进了我的嘴里。我尝试着吃了一口，“噗”——好浓烈古怪的味道。“哇～～～哇～～～哇～～～“ 我想要水池的味道。隐隐约约的，我好像知道水池是妈妈。可是就像当初被强行推出水池一样，我再也没能吃到水池的味道。

那天起，我吃到了好多种稀奇古怪难吃的味道。为什么就不能像最初的食物那样味道简单呢？

就这样，每次看见有东西向我移动，我都很紧张，很怕又被塞一嘴怪味儿。不高兴时“噗～～～噗～～～”的把塞进嘴里的都喷出去，饿的时候就勉强咽下，再哼哼几声。慢慢的，我看得越来越清楚，四肢越来越有力。只要没人按着我，我就可以挥动四肢，阻挠他们把那硬硬的瓶子的嘴儿塞给我。

这一天，我见到了一个和我一样，需要很用力才能翻身，但是翻了几个身就可以滚离原地很远的团子。我听见一些叽叽喳喳的声音，但不知道他们在做什么。在他们又往我嘴里塞瓶嘴儿的时候，我很机灵的往旁边一翻，“啪”，压在了团子的身上。我吭哧吭哧的想再翻一下，从团子身上下来，可是怎么都使不上力气。这时，我和小团子被人分别抱起。我见到有人过来，顺着她的动作，看见她端着什么喂团子。凭什么团子不是用难吃的瓶子吃饭？我“啊～啊～”的努力问着团子，只见团子面前的东西转了个方向，递到了我的嘴边。我心想：“吃了那么多难吃的东西，还能被你吓住？看我不喷你。” 我张大了嘴巴，一口含住了小勺子，奇迹般的，竟然不是浓烈到让我无所适从的味道！我忍了又忍，还是不忍心把这口有些粘稠的好吃哒喷出去。不由自主的咽下，又张大了嘴巴“啊～啊～”，又一口。哈哈哈，好开心，终于不是难吃的瓶子了！宝宝遇见好吃哒啦！终于可以吃饱饭，安心的睡觉觉了。

**Comment by wwmm111** [comment]
> **爸爸的视角**

我叫李大乐，年过而立才得一子，刚做奶爸一年半（从宝宝萌芽算起）。初为人父，我美得走路生风。后继有人的踏实感令我每天不干活儿都难受。有一天发现太太没有奶水，给孩子准备了坊间有名的配方奶粉，孩子却时常吐出来不吃，偶尔咽下几口也是瘪着嘴要哭不哭的哼哼。换了其他更贵的奶液也是一样。我好奇之下尝了尝这些配方奶的味道，觉得不错呀，孩子为什么不喝呢？直到有一天，看见儿子李来宝抢了其他小朋友的米糊吃得一口接一口的，我忍不住尝了尝米糊，却惊讶的发现寡淡无味得很。原来，初生为人的娃娃，喜欢简单纯粹的味道。

**Comment by Freshniu** [comment]
大体故事出来就好办。以下细节再修改。
> 我好奇之下尝了尝这些配方奶的味道，觉得不错呀，孩子为什么不喝呢？

**Comment by wwmm111** [comment]
> **妈妈的视角**

3. 我叫金凤，年近而立才做母亲，我家来宝刚满六个月。初初见到来宝，被他皱得有点青瘀的样子惊得不相信他是我儿子。直到看着他闭着眼睛在我怀里吃奶，小小的一只，还睡着就知道吭哧吭哧的吃。我的心瞬间化成一团团棉花，恨不得保护他一辈子不知痛是什么。随着产假结束、我开始上班，奶水慢慢减少了。工作压力增大，我不得不狠心给孩子断了奶，改喂精心挑选的名牌配方奶。来宝起初不吃，总是噗噗的吐。本以为过段时间习惯了就好，听说很多孩子都有这个时期。可谁知来宝是个有脾气的。饿狠了吃两口，还要瘪瘪嘴、哼哼几声。大多数时候，是吃一口吐三口。我和孩子爸爸又心疼孩子又生气，急得夜不能寐、食不下咽。孰料有一天，带来宝去朋友家玩儿，他竟然抢了朋友家同龄的孩子的米糊吃，还吃得津津有味儿。起初我和宝宝爸爸都担心的等着宝宝的哭闹和不良反应，谁知他大概是真的吃饱且吃得舒服，睡了长长的安稳觉，没哭没闹。和朋友求教，才知道这米糊的玄机。宝宝的味觉还在慢慢的发展，受不得强烈的味道，稍稍一点点滋味就欢喜得不得了，最喜欢简单、纯粹的食物。这米糊什么都未加，只用天然野生的黑米磨粉做成，简简单单，却是宝宝喜爱的真滋味。有了黑米粉，终于不用担心来宝不吃东西、营养跟不上、发育迟缓了。我终于睡了个好觉。

**Comment by Freshniu** [comment]
以下细节：
> 我好奇之下尝了尝这些配方奶的味道
- 真实情况是大部分家长都不会觉得配方奶好喝。 参考[为什么婴儿奶粉味道不好，很难吃](http://www.sohu.com/a/63450985_387763)
-建议：去掉这句话。

> 宝宝的味觉还在慢慢的发展，受不得强烈的味道
- 真实情况是宝宝吃惯重口味就不爱清淡口味。
- 建议：去掉这句话。

> 我开始上班，奶水慢慢减少了。工作压力增大，我不得不狠心给孩子断了奶
- 这个不算是必须断奶的理由。
- 就说奶水少的可怜，不说断奶。或者加大冲突，说因病服药必须断奶。
